version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - test
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 5
